Add public method to upfront check if call in cache and valid
joblib/joblib pull request #1584
Opened 2024-05-18 22:05 UTC by LudwigStumpp

Following the reasoning and implementation behind #820, this PR adds a public method to check if a given cached function call is in cache and valid (=meets the cache validation callback function).

2024-05-18 23:27 UTC, LudwigStumpp commented
> ## [Codecov](https://app.codecov.io/gh/joblib/joblib/pull/1584?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=joblib) Report
> 
> All modified and coverable lines are covered by tests ✅
> 
> > Project coverage is 95.22%. Comparing base [(`dc0cb6d`)](https://app.codecov.io/gh/joblib/joblib/commit/dc0cb6d02dd9f43db76a0583542bc5da0f9d4b03?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=joblib) to head [(`35bc127`)](https://app.codecov.io/gh/joblib/joblib/pull/1584?dropdown=coverage&src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=joblib).
> 
> Additional details and impacted files
> 
> ```diff
> @@            Coverage Diff             @@
> ##             main    #1584      +/-   ##
> ==========================================
> - Coverage   95.23%   95.22%   -0.02%     
> ==========================================
>   Files          45       45              
>   Lines        7705     7725      +20     
> ==========================================
> + Hits         7338     7356      +18     
> - Misses        367      369       +2     
> ```
> 
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/joblib/joblib/pull/1584?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=joblib). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=joblib).

Anyone has a clue where the increase of +2 misses comes from?

2024-05-21 07:26 UTC, tomMoral requested changes
Hello,

Thanks for the proposal. I think this is the intent of the `check_call_in_cache` method.

Instead of adding an extra method, I would avoid duplication and modify the existing method to include checking that the cache is valid.

2024-05-21 07:26 UTC, tomMoral commented on joblib/memory.py
> +
```suggestion
```

2024-05-21 07:26 UTC, tomMoral commented on joblib/memory.py
> +        return self._is_in_cache_and_valid(call_id)
```suggestion
        return self._is_in_cache_and_valid(call_id)
```

2024-05-21 07:26 UTC, tomMoral commented on joblib/test/test_memory.py
> +        result = func.is_call_in_cache_and_valid(2)
```suggestion
        result = func.check_call_in_cache(2)
        assert isinstance(result, bool)
        assert not result
        assert func(2) == 5
        result = func.check_in_cache(2)
```

2024-05-21 07:26 UTC, tomMoral commented on joblib/test/test_memory.py
> +    assert not func.is_call_in_cache_and_valid(2)
```suggestion
    assert not func.check_call_in_cache(2)
```

2024-05-24 20:22 UTC, LudwigStumpp commented
Hello Tom, yeah, I agree with your proposal of instead improving / fixing the already present `check_call_in_cache` and will update accordingly.

2024-05-24 20:56 UTC, LudwigStumpp commented
@tomMoral I just moved the functionality over to the already existing `check_call_in_cache` method but unfortunately got some errors which to me however seem unrelated to the change I did - however maybe I am missing something. Could you please take a look?

2024-05-24 21:54 UTC, tomMoral approved these changes
LGTM!

2024-05-24 21:54 UTC, tomMoral commented on joblib/memory.py
> +        bool:
```suggestion
        is_call_in_cache: bool
```

2024-05-24 21:59 UTC, tomMoral commented
it seems that the failure is unrelated, could you push a every in the change log?

2024-06-14 10:37 UTC, LudwigStumpp commented
@tomMoral I added a section in the change log. Apart from above docs build error that I still seem to be getting, I would be good to go.

2024-06-14 11:59 UTC, tomMoral approved these changes
LGTM

2024-06-14 14:34 UTC, tomMoral commented on joblib/memory.py
> +        asserting if it has changed.
I think the doc build failure is coming from this line

```suggestion
          asserting if it has changed.
```

2024-06-14 15:23 UTC, merged

2025-01-23 14:42 UTC, valankar commented
Any idea when this might be released? Just came across the issue thinking check_call_in_cache verifies the cache_validation_callback, but it does not (v1.4.2). Thanks.

2025-01-23 21:01 UTC, tomMoral commented
We plan to do a sprint and a release in late February.
Sorry for the delay in the release of this feature.